# Generated by Django 5.1.6 on 2025-02-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networknode',
            options={'ordering': ['name']},
        ),
    ]
